const Issue = require('../models/Issue');
const User = require('../models/User'); // Assuming your user model is here

// @desc    Create a new issue report
// @route   POST /api/issues
// @access  Private (requires user authentication)
const createIssue = async (req, res) => {
  try {
    const {
      category,
      description,
      location, // Expecting { address: '...', coordinates: [lng, lat] }
      landmark,
      photos // Expecting an array of image URLs
    } = req.body;

    // TODO: Get userId from authenticated request (e.g., req.user.id)
    // Replace 'PLACEHOLDER_USER_ID' with actual user ID from auth middleware
    const userId = req.user.id; // Assuming auth middleware adds user object to req

    if (!category || !description || !location || !location.address) {
        return res.status(400).json({ message: 'Missing required fields (category, description, location address)' });
    }

    const newIssue = new Issue({
      category,
      description,
      location: {
        address: location.address,
        // Only add coordinates if provided and valid
        ...(location.coordinates && location.coordinates.length === 2 && {
            type: 'Point',
            coordinates: location.coordinates
        })
      },
      landmark,
      photos: photos || [],
      reportedBy: userId,
      // complaintId will be generated by the pre-save hook in the model
    });

    const savedIssue = await newIssue.save();

    res.status(201).json({ message: 'Issue reported successfully', issue: savedIssue });

  } catch (error) {
    console.error('Error creating issue:', error);
    // Handle potential duplicate complaintId error if generated here instead of model
    if (error.code === 11000) {
        return res.status(400).json({ message: 'Error generating unique complaint ID. Please try again.' });
    }
    res.status(500).json({ message: 'Server error reporting issue', error: error.message });
  }
};

// @desc    Get all issue reports (for Admin)
// @route   GET /api/issues
// @access  Private (Admin)
const getIssues = async (req, res) => {
  try {
    // Fetch issues and populate the 'reportedBy' field with user's email
    // Assumes your User model has an 'email' field
    const issues = await Issue.find()
                                .populate('reportedBy', 'email') // Select only the email field from User
                                .sort({ createdAt: -1 }); // Show newest first

    res.status(200).json(issues);
  } catch (error) {
    console.error('Error fetching issues:', error);
    res.status(500).json({ message: 'Server error fetching issues', error: error.message });
  }
};

// @desc    Get a single issue report by ID (for Admin view details)
// @route   GET /api/issues/:id
// @access  Private (Admin)
const getIssueById = async (req, res) => {
  try {
    const issue = await Issue.findById(req.params.id)
                             .populate('reportedBy', 'email name'); // Populate with email and name if available

    if (!issue) {
      return res.status(404).json({ message: 'Issue not found' });
    }

    res.status(200).json(issue);
  } catch (error) {
    console.error('Error fetching issue by ID:', error);
    // Handle potential CastError if ID format is invalid
    if (error.name === 'CastError') {
        return res.status(400).json({ message: 'Invalid issue ID format' });
    }
    res.status(500).json({ message: 'Server error fetching issue details', error: error.message });
  }
};

// @desc    Update issue status or feedback (for Admin)
// @route   PUT /api/issues/:id
// @access  Private (Admin)
const updateIssue = async (req, res) => {
    try {
        const { status, adminFeedback } = req.body;
        const issueId = req.params.id;

        const issue = await Issue.findById(issueId);

        if (!issue) {
            return res.status(404).json({ message: 'Issue not found' });
        }

        // Update fields if they are provided in the request body
        if (status) {
            // Validate status against enum values
            const allowedStatuses = ['Pending', 'In Progress', 'Resolved', 'Rejected'];
            if (!allowedStatuses.includes(status)) {
                return res.status(400).json({ message: `Invalid status value. Must be one of: ${allowedStatuses.join(', ')}` });
            }
            issue.status = status;
        }
        if (adminFeedback !== undefined) { // Allow setting feedback to empty string
            issue.adminFeedback = adminFeedback;
        }

        const updatedIssue = await issue.save();

        // Consider populating reportedBy again if needed on the frontend after update
        res.status(200).json({ message: 'Issue updated successfully', issue: updatedIssue });

    } catch (error) {
        console.error('Error updating issue:', error);
        if (error.name === 'CastError') {
            return res.status(400).json({ message: 'Invalid issue ID format' });
        }
        res.status(500).json({ message: 'Server error updating issue', error: error.message });
    }
};

// @desc    Get current user's issues
// @route   GET /api/issues/my
// @access  Private
const getMyIssues = async (req, res) => {
  try {
    const issues = await Issue.find({ reportedBy: req.user.id })
                              .sort({ createdAt: -1 });

    res.status(200).json(issues);
  } catch (error) {
    console.error('Error fetching user issues:', error);
    res.status(500).json({ message: 'Server error fetching your issues', error: error.message });
  }
};


module.exports = {
  createIssue,
  getIssues,
  getIssueById,
  updateIssue,
  getMyIssues,
};
